name: "Sample Python Setup workflow"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs: 
    python-setup-job:
        runs-on: ubuntu-latest

        steps:
            - name: "Setup python"
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"

            - name: "Check python version"
              run: python --version

            - name: "Clone the repo"
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run: pip install -r requirements.txt

            - name: "Run script"
              run: python3 script.py
            